/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealsIndexRouteImport } from './routes/meals/index'
import { Route as FoodsIndexRouteImport } from './routes/foods/index'
import { Route as UsersMeRouteImport } from './routes/users/me'
import { Route as MealsAddRouteImport } from './routes/meals/add'
import { Route as MealsIdRouteImport } from './routes/meals/$id'
import { Route as FoodsIdRouteImport } from './routes/foods/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsIndexRoute = MealsIndexRouteImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsIndexRoute = FoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersMeRoute = UsersMeRouteImport.update({
  id: '/users/me',
  path: '/users/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsAddRoute = MealsAddRouteImport.update({
  id: '/meals/add',
  path: '/meals/add',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsIdRoute = MealsIdRouteImport.update({
  id: '/meals/$id',
  path: '/meals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsIdRoute = FoodsIdRouteImport.update({
  id: '/foods/$id',
  path: '/foods/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foods/$id': typeof FoodsIdRoute
  '/meals/$id': typeof MealsIdRoute
  '/meals/add': typeof MealsAddRoute
  '/users/me': typeof UsersMeRoute
  '/foods/': typeof FoodsIndexRoute
  '/meals/': typeof MealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foods/$id': typeof FoodsIdRoute
  '/meals/$id': typeof MealsIdRoute
  '/meals/add': typeof MealsAddRoute
  '/users/me': typeof UsersMeRoute
  '/foods': typeof FoodsIndexRoute
  '/meals': typeof MealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foods/$id': typeof FoodsIdRoute
  '/meals/$id': typeof MealsIdRoute
  '/meals/add': typeof MealsAddRoute
  '/users/me': typeof UsersMeRoute
  '/foods/': typeof FoodsIndexRoute
  '/meals/': typeof MealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/foods/$id'
    | '/meals/$id'
    | '/meals/add'
    | '/users/me'
    | '/foods/'
    | '/meals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/foods/$id'
    | '/meals/$id'
    | '/meals/add'
    | '/users/me'
    | '/foods'
    | '/meals'
  id:
    | '__root__'
    | '/'
    | '/foods/$id'
    | '/meals/$id'
    | '/meals/add'
    | '/users/me'
    | '/foods/'
    | '/meals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoodsIdRoute: typeof FoodsIdRoute
  MealsIdRoute: typeof MealsIdRoute
  MealsAddRoute: typeof MealsAddRoute
  UsersMeRoute: typeof UsersMeRoute
  FoodsIndexRoute: typeof FoodsIndexRoute
  MealsIndexRoute: typeof MealsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/': {
      id: '/meals/'
      path: '/meals'
      fullPath: '/meals/'
      preLoaderRoute: typeof MealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/': {
      id: '/foods/'
      path: '/foods'
      fullPath: '/foods/'
      preLoaderRoute: typeof FoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/me': {
      id: '/users/me'
      path: '/users/me'
      fullPath: '/users/me'
      preLoaderRoute: typeof UsersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/add': {
      id: '/meals/add'
      path: '/meals/add'
      fullPath: '/meals/add'
      preLoaderRoute: typeof MealsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/$id': {
      id: '/meals/$id'
      path: '/meals/$id'
      fullPath: '/meals/$id'
      preLoaderRoute: typeof MealsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/$id': {
      id: '/foods/$id'
      path: '/foods/$id'
      fullPath: '/foods/$id'
      preLoaderRoute: typeof FoodsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoodsIdRoute: FoodsIdRoute,
  MealsIdRoute: MealsIdRoute,
  MealsAddRoute: MealsAddRoute,
  UsersMeRoute: UsersMeRoute,
  FoodsIndexRoute: FoodsIndexRoute,
  MealsIndexRoute: MealsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
