/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodsIndexRouteImport } from './routes/foods/index'
import { Route as FoodsIdRouteImport } from './routes/foods/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsIndexRoute = FoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsIdRoute = FoodsIdRouteImport.update({
  id: '/foods/$id',
  path: '/foods/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foods/$id': typeof FoodsIdRoute
  '/foods/': typeof FoodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foods/$id': typeof FoodsIdRoute
  '/foods': typeof FoodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foods/$id': typeof FoodsIdRoute
  '/foods/': typeof FoodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/foods/$id' | '/foods/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/foods/$id' | '/foods'
  id: '__root__' | '/' | '/foods/$id' | '/foods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoodsIdRoute: typeof FoodsIdRoute
  FoodsIndexRoute: typeof FoodsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/': {
      id: '/foods/'
      path: '/foods'
      fullPath: '/foods/'
      preLoaderRoute: typeof FoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/$id': {
      id: '/foods/$id'
      path: '/foods/$id'
      fullPath: '/foods/$id'
      preLoaderRoute: typeof FoodsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoodsIdRoute: FoodsIdRoute,
  FoodsIndexRoute: FoodsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
